// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: buyingGRPC.proto

package buyingGRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Buying_Buying_FullMethodName = "/buying.Buying/Buying"
)

// BuyingClient is the client API for Buying service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuyingClient interface {
	Buying(ctx context.Context, in *BuyingRequest, opts ...grpc.CallOption) (*BuyingReply, error)
}

type buyingClient struct {
	cc grpc.ClientConnInterface
}

func NewBuyingClient(cc grpc.ClientConnInterface) BuyingClient {
	return &buyingClient{cc}
}

func (c *buyingClient) Buying(ctx context.Context, in *BuyingRequest, opts ...grpc.CallOption) (*BuyingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyingReply)
	err := c.cc.Invoke(ctx, Buying_Buying_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuyingServer is the server API for Buying service.
// All implementations must embed UnimplementedBuyingServer
// for forward compatibility.
type BuyingServer interface {
	Buying(context.Context, *BuyingRequest) (*BuyingReply, error)
	mustEmbedUnimplementedBuyingServer()
}

// UnimplementedBuyingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuyingServer struct{}

func (UnimplementedBuyingServer) Buying(context.Context, *BuyingRequest) (*BuyingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buying not implemented")
}
func (UnimplementedBuyingServer) mustEmbedUnimplementedBuyingServer() {}
func (UnimplementedBuyingServer) testEmbeddedByValue()                {}

// UnsafeBuyingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuyingServer will
// result in compilation errors.
type UnsafeBuyingServer interface {
	mustEmbedUnimplementedBuyingServer()
}

func RegisterBuyingServer(s grpc.ServiceRegistrar, srv BuyingServer) {
	// If the following call pancis, it indicates UnimplementedBuyingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Buying_ServiceDesc, srv)
}

func _Buying_Buying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuyingServer).Buying(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Buying_Buying_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuyingServer).Buying(ctx, req.(*BuyingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Buying_ServiceDesc is the grpc.ServiceDesc for Buying service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Buying_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buying.Buying",
	HandlerType: (*BuyingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Buying",
			Handler:    _Buying_Buying_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buyingGRPC.proto",
}
