// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: buyingGRPC.proto

package buyingGRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pin           int32                  `protobuf:"varint,2,opt,name=pin,proto3" json:"pin,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyingRequest) Reset() {
	*x = BuyingRequest{}
	mi := &file_buyingGRPC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyingRequest) ProtoMessage() {}

func (x *BuyingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buyingGRPC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyingRequest.ProtoReflect.Descriptor instead.
func (*BuyingRequest) Descriptor() ([]byte, []int) {
	return file_buyingGRPC_proto_rawDescGZIP(), []int{0}
}

func (x *BuyingRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BuyingRequest) GetPin() int32 {
	if x != nil {
		return x.Pin
	}
	return 0
}

func (x *BuyingRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyingReply) Reset() {
	*x = BuyingReply{}
	mi := &file_buyingGRPC_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyingReply) ProtoMessage() {}

func (x *BuyingReply) ProtoReflect() protoreflect.Message {
	mi := &file_buyingGRPC_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyingReply.ProtoReflect.Descriptor instead.
func (*BuyingReply) Descriptor() ([]byte, []int) {
	return file_buyingGRPC_proto_rawDescGZIP(), []int{1}
}

func (x *BuyingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_buyingGRPC_proto protoreflect.FileDescriptor

const file_buyingGRPC_proto_rawDesc = "" +
	"\n" +
	"\x10buyingGRPC.proto\x12\x06buying\"O\n" +
	"\rBuyingRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\x05R\x03pin\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"'\n" +
	"\vBuyingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2>\n" +
	"\x06Buying\x124\n" +
	"\x06Buying\x12\x15.buying.BuyingRequest\x1a\x13.buying.BuyingReplyB&Z$github.com/epic55/BankApp/buyingGRPCb\x06proto3"

var (
	file_buyingGRPC_proto_rawDescOnce sync.Once
	file_buyingGRPC_proto_rawDescData []byte
)

func file_buyingGRPC_proto_rawDescGZIP() []byte {
	file_buyingGRPC_proto_rawDescOnce.Do(func() {
		file_buyingGRPC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buyingGRPC_proto_rawDesc), len(file_buyingGRPC_proto_rawDesc)))
	})
	return file_buyingGRPC_proto_rawDescData
}

var file_buyingGRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_buyingGRPC_proto_goTypes = []any{
	(*BuyingRequest)(nil), // 0: buying.BuyingRequest
	(*BuyingReply)(nil),   // 1: buying.BuyingReply
}
var file_buyingGRPC_proto_depIdxs = []int32{
	0, // 0: buying.Buying.Buying:input_type -> buying.BuyingRequest
	1, // 1: buying.Buying.Buying:output_type -> buying.BuyingReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buyingGRPC_proto_init() }
func file_buyingGRPC_proto_init() {
	if File_buyingGRPC_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buyingGRPC_proto_rawDesc), len(file_buyingGRPC_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buyingGRPC_proto_goTypes,
		DependencyIndexes: file_buyingGRPC_proto_depIdxs,
		MessageInfos:      file_buyingGRPC_proto_msgTypes,
	}.Build()
	File_buyingGRPC_proto = out.File
	file_buyingGRPC_proto_goTypes = nil
	file_buyingGRPC_proto_depIdxs = nil
}
